version: '3'

volumes:
  kafka:
    driver: local
  zookeeper:
    driver: local

services:
  rivulet:
    build:
      context: .
      args:
        - MIX_ENV=dev
    command: echo "Not an app"
    environment:
      HOSTNAME: host1
    depends_on:
      - kafka
      - schema-registry
    volumes:
      - .:/app
  kafka:
    image: confluentinc/cp-kafka:3.3.0
    hostname: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - kafka:/var/lib/kafka/data
    restart: on-failure
  zookeeper:
    image: confluentinc/cp-zookeeper:3.3.0
    ports:
      - "2181:2181"
    volumes:
      - zookeeper:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  schema-registry:
    image: confluentinc/cp-schema-registry:3.3.0
    hostname: kafkaschema
    depends_on:
      - kafka
      - zookeeper
    links:
      - kafka
      - zookeeper:confluent
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: kafkaschema
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "confluent:2181"
